-- Production schema for the LAZARUS basketball strategies.
-- One row per match tick. Every feature column is DOUBLE PRECISION and
-- NULLABLE: a NULL means "not yet determined", and a NULL NEVER satisfies
-- a condition. Do not default these to 0.

CREATE TABLE IF NOT EXISTS laz_tick (
  match_id      TEXT        NOT NULL,
  ts            TIMESTAMPTZ NOT NULL,
  league        TEXT,
  phase         TEXT,
  h_score       INTEGER,
  a_score       INTEGER,
  home_odds     DOUBLE PRECISION,
  away_odds     DOUBLE PRECISION,
  draw_odds     DOUBLE PRECISION,
  total_points_handicap DOUBLE PRECISION,
  total_points_over     DOUBLE PRECISION,
  total_points_under    DOUBLE PRECISION,
  market_status TEXT,
  "X_X_minute__x__u_pace__minus__X_u_elapsed__minus__u_time_in_lead" DOUBLE PRECISION,
  "X_X_u_elapsed__minus__u_time_in_lead__minus__X_u_pace__over__u_time_in_lead" DOUBLE PRECISION,
  "X_X_u_elapsed__minus__u_time_in_lead__over__X_u_pace__over__u_time_in_lead" DOUBLE PRECISION,
  "X_a_score__over__home_odds"           DOUBLE PRECISION,
  "X_home_odds__x__point_spread_away"    DOUBLE PRECISION,
  "X_minute__minus__u_drought"           DOUBLE PRECISION,
  "X_minute__over__u_elapsed"            DOUBLE PRECISION,
  "X_minute__over__u_pace"               DOUBLE PRECISION,
  "X_minute__over__u_vol"                DOUBLE PRECISION,
  "X_minute__x__u_pace"                  DOUBLE PRECISION,
  "X_point_spread_home__x__q1_lead"      DOUBLE PRECISION,
  "X_q1_lead__minus__u_overround"        DOUBLE PRECISION,
  "X_u_elapsed__minus__u_time_in_lead"   DOUBLE PRECISION,
  "X_u_elapsed__x__u_time_in_lead"       DOUBLE PRECISION,
  "abs_margin_per_remaining_s"           DOUBLE PRECISION,
  "away_odds"                            DOUBLE PRECISION,
  "backed_pts_last_60s"                  DOUBLE PRECISION,
  "both_scored"                          DOUBLE PRECISION,
  "clean_sheet"                          DOUBLE PRECISION,
  "dog_odds_trend_60"                    DOUBLE PRECISION,
  "dog_odds_vol_180"                     DOUBLE PRECISION,
  "dow"                                  DOUBLE PRECISION,
  "dp_lead_open"                         DOUBLE PRECISION,
  "drift_ratio"                          DOUBLE PRECISION,
  "eng_minute_ge_2"                      DOUBLE PRECISION,
  "eng_score_tied"                       DOUBLE PRECISION,
  "fav_lead_m30"                         DOUBLE PRECISION,
  "fav_odds_trend_60"                    DOUBLE PRECISION,
  "h_score"                              DOUBLE PRECISION,
  "home_odds"                            DOUBLE PRECISION,
  "home_pace"                            DOUBLE PRECISION,
  "hour"                                 DOUBLE PRECISION,
  "imbal"                                DOUBLE PRECISION,
  "imp_away"                             DOUBLE PRECISION,
  "is_big_lead"                          DOUBLE PRECISION,
  "is_favorite"                          DOUBLE PRECISION,
  "is_trailer"                           DOUBLE PRECISION,
  "jump_loser"                           DOUBLE PRECISION,
  "ld_rank"                              DOUBLE PRECISION,
  "lead_age_s"                           DOUBLE PRECISION,
  "lead_change_last_300s"                DOUBLE PRECISION,
  "lead_changes_300s"                    DOUBLE PRECISION,
  "lead_changes_total"                   DOUBLE PRECISION,
  "lead_delta_last_120s"                 DOUBLE PRECISION,
  "lead_jump"                            DOUBLE PRECISION,
  "lead_m15"                             DOUBLE PRECISION,
  "lead_m30"                             DOUBLE PRECISION,
  "lead_m75"                             DOUBLE PRECISION,
  "lead_margin_m30"                      DOUBLE PRECISION,
  "lead_odds"                            DOUBLE PRECISION,
  "lead_poss"                            DOUBLE PRECISION,
  "lead_size"                            DOUBLE PRECISION,
  "lead_vs_line"                         DOUBLE PRECISION,
  "lead_vs_med"                          DOUBLE PRECISION,
  "lead_vs_prematch_gap"                 DOUBLE PRECISION,
  "leader_drift"                         DOUBLE PRECISION,
  "leader_implied_gap"                   DOUBLE PRECISION,
  "leader_runmax"                        DOUBLE PRECISION,
  "line"                                 DOUBLE PRECISION,
  "line_flat"                            DOUBLE PRECISION,
  "line_move"                            DOUBLE PRECISION,
  "line_open"                            DOUBLE PRECISION,
  "line_vel"                             DOUBLE PRECISION,
  "loser_runmax"                         DOUBLE PRECISION,
  "loser_runmin"                         DOUBLE PRECISION,
  "margin_per_implied"                   DOUBLE PRECISION,
  "margin_per_possession"                DOUBLE PRECISION,
  "margin_range_300s"                    DOUBLE PRECISION,
  "margin_rate"                          DOUBLE PRECISION,
  "motif_0"                              DOUBLE PRECISION,
  "motif_1"                              DOUBLE PRECISION,
  "motif_2"                              DOUBLE PRECISION,
  "nchg_120"                             DOUBLE PRECISION,
  "need_frac"                            DOUBLE PRECISION,
  "need_vs_expected"                     DOUBLE PRECISION,
  "needed_rate_for_over"                 DOUBLE PRECISION,
  "odds_ratio"                           DOUBLE PRECISION,
  "open_gap"                             DOUBLE PRECISION,
  "open_vs_now_lead"                     DOUBLE PRECISION,
  "opp"                                  DOUBLE PRECISION,
  "opp_drift"                            DOUBLE PRECISION,
  "opp_o"                                DOUBLE PRECISION,
  "opp_pts_last_60s"                     DOUBLE PRECISION,
  "opp_velocity"                         DOUBLE PRECISION,
  "overround_now"                        DOUBLE PRECISION,
  "pace_last_300s_vs_line"               DOUBLE PRECISION,
  "pace_vs_line_pct"                     DOUBLE PRECISION,
  "pm_away"                              DOUBLE PRECISION,
  "pm_home"                              DOUBLE PRECISION,
  "pm_ratio"                             DOUBLE PRECISION,
  "point_spread_handicap"                DOUBLE PRECISION,
  "point_spread_home"                    DOUBLE PRECISION,
  "prematch_dog_odds"                    DOUBLE PRECISION,
  "price_gap"                            DOUBLE PRECISION,
  "price_move_since_score"               DOUBLE PRECISION,
  "price_rank_in_match"                  DOUBLE PRECISION,
  "prog"                                 DOUBLE PRECISION,
  "prog_period"                          DOUBLE PRECISION,
  "prog_q"                               DOUBLE PRECISION,
  "prog_score"                           DOUBLE PRECISION,
  "prog_x_margin"                        DOUBLE PRECISION,
  "proj_gap_n"                           DOUBLE PRECISION,
  "pts_last_60s"                         DOUBLE PRECISION,
  "px_gap_ratio"                         DOUBLE PRECISION,
  "q"                                    DOUBLE PRECISION,
  "recovery_x"                           DOUBLE PRECISION,
  "req_ratio"                            DOUBLE PRECISION,
  "retrace_lead"                         DOUBLE PRECISION,
  "retrace_lo"                           DOUBLE PRECISION,
  "rk_dog_odds"                          DOUBLE PRECISION,
  "rk_fav_odds"                          DOUBLE PRECISION,
  "rk_implied_edge"                      DOUBLE PRECISION,
  "rk_lead_off_high"                     DOUBLE PRECISION,
  "rk_lead_off_low"                      DOUBLE PRECISION,
  "rk_odds_ratio"                        DOUBLE PRECISION,
  "runmin"                               DOUBLE PRECISION,
  "scores_300s"                          DOUBLE PRECISION,
  "scoring_rate"                         DOUBLE PRECISION,
  "secs_since_price"                     DOUBLE PRECISION,
  "secs_since_quarter_start"             DOUBLE PRECISION,
  "secs_since_run_started"               DOUBLE PRECISION,
  "secs_since_score"                     DOUBLE PRECISION,
  "spread_cover_now"                     DOUBLE PRECISION,
  "ten_mins"                             DOUBLE PRECISION,
  "tg_imp_over"                          DOUBLE PRECISION,
  "tg_imp_under"                         DOUBLE PRECISION,
  "tg_overround"                         DOUBLE PRECISION,
  "tg_proj_vs_line"                      DOUBLE PRECISION,
  "tg_px_ratio"                          DOUBLE PRECISION,
  "time_at_this_price"                   DOUBLE PRECISION,
  "time_left"                            DOUBLE PRECISION,
  "tot_vs_line"                          DOUBLE PRECISION,
  "total_goals_handicap_ffill"           DOUBLE PRECISION,
  "total_line_move"                      DOUBLE PRECISION,
  "total_points_handicap"                DOUBLE PRECISION,
  "total_points_over"                    DOUBLE PRECISION,
  "total_points_under"                   DOUBLE PRECISION,
  "total_pts"                            DOUBLE PRECISION,
  "tp_vel_n"                             DOUBLE PRECISION,
  "trail"                                DOUBLE PRECISION,
  "trailer_drift"                        DOUBLE PRECISION,
  "trailer_price"                        DOUBLE PRECISION,
  "u_drift"                              DOUBLE PRECISION,
  "u_drift_opp"                          DOUBLE PRECISION,
  "u_drought"                            DOUBLE PRECISION,
  "u_flat"                               DOUBLE PRECISION,
  "u_hazard"                             DOUBLE PRECISION,
  "u_jump"                               DOUBLE PRECISION,
  "u_margin_abs"                         DOUBLE PRECISION,
  "u_open"                               DOUBLE PRECISION,
  "u_overround"                          DOUBLE PRECISION,
  "u_pace"                               DOUBLE PRECISION,
  "u_price"                              DOUBLE PRECISION,
  "u_price_open"                         DOUBLE PRECISION,
  "u_ratio_open"                         DOUBLE PRECISION,
  "u_ratio_shift"                        DOUBLE PRECISION,
  "u_time_in_lead"                       DOUBLE PRECISION,
  "u_trend"                              DOUBLE PRECISION,
  "u_vel_t"                              DOUBLE PRECISION,
  "u_vf"                                 DOUBLE PRECISION,
  "u_vol"                                DOUBLE PRECISION,
  "wall_min"                             DOUBLE PRECISION,
  PRIMARY KEY (match_id, ts)
);

CREATE INDEX IF NOT EXISTS laz_tick_match_ts ON laz_tick (match_id, ts);

CREATE TABLE IF NOT EXISTS laz_bet (
  strategy   TEXT        NOT NULL,
  match_id   TEXT        NOT NULL,
  ts         TIMESTAMPTZ NOT NULL,
  price      DOUBLE PRECISION NOT NULL,
  side       TEXT,
  placed_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (strategy, match_id)   -- ONE BET PER MATCH PER STRATEGY
);
