# laz_pca_features_basketball.py — GENERATED BY THE ENGINE. DO NOT EDIT BY HAND.
#
# Every transform below was FROZEN when the engine fitted it on the in-sample
# rows of this run and is reproduced here exactly: the cluster terms in their
# fitted order, the per-term mean and standard deviation, and the first
# principal component loading.  pc = (((x - mu) / sdv) . w), emitted as the
# same float32 the sweep measured on.
#
# A tick on which ANY input term is missing or non-finite yields None, never 0:
# the fit itself dropped exactly those rows, so a 0 would be a value the engine
# never saw and the condition would test a number that does not exist.
#
# engine   : engine_e2e_test
# sport    : basketball
# composites: 6

import math as _math

PCA = {
    'pc_2f7f4d0c': dict(
        terms=['line_move', 'line_open', 'wall_min'],
        mu=[1.0, 2.0, 3.0],
        sdv=[0.5, 1.5, 2.5],
        w=[0.6, -0.5, 0.62],
        n_fit=1200),
    'pc_428f55cf': dict(
        terms=['line_move', 'line_open', 'wall_min'],
        mu=[1.0, 2.0, 3.0],
        sdv=[0.5, 1.5, 2.5],
        w=[0.6, -0.5, 0.62],
        n_fit=1200),
    'pc_51f228a2': dict(
        terms=['line_move', 'line_open', 'wall_min'],
        mu=[1.0, 2.0, 3.0],
        sdv=[0.5, 1.5, 2.5],
        w=[0.6, -0.5, 0.62],
        n_fit=1200),
    'pc_aa16b0a5': dict(
        terms=['line_move', 'line_open', 'wall_min'],
        mu=[1.0, 2.0, 3.0],
        sdv=[0.5, 1.5, 2.5],
        w=[0.6, -0.5, 0.62],
        n_fit=1200),
    'pc_f3e46219': dict(
        terms=['line_move', 'line_open', 'wall_min'],
        mu=[1.0, 2.0, 3.0],
        sdv=[0.5, 1.5, 2.5],
        w=[0.6, -0.5, 0.62],
        n_fit=1200),
    'pc_fea3bd2c': dict(
        terms=['line_move', 'line_open', 'wall_min'],
        mu=[1.0, 2.0, 3.0],
        sdv=[0.5, 1.5, 2.5],
        w=[0.6, -0.5, 0.62],
        n_fit=1200),
}


def _f32(x):
    """The engine emitted float32. Rounding here and not there would put a
    value on the other side of a threshold fitted to the float32."""
    import struct
    return struct.unpack("<f", struct.pack("<f", x))[0]


def compute(f):
    """Fold every frozen composite into the feature dict `f`, in place.

    Call this AFTER the sport features and the book features are merged, so
    every input term is present, and BEFORE conditions are evaluated.
    Returns `f`.
    """
    for name, spec in PCA.items():
        acc = 0.0
        ok = True
        for t, mu, sd, w in zip(spec["terms"], spec["mu"], spec["sdv"], spec["w"]):
            v = f.get(t)
            if v is None:
                ok = False
                break
            try:
                v = float(v)
            except (TypeError, ValueError):
                ok = False
                break
            if v != v or v in (float("inf"), float("-inf")):
                ok = False
                break
            acc += ((v - mu) / sd) * w
        f[name] = _f32(acc) if (ok and not _math.isinf(acc) and acc == acc) else None
    return f
